### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [zwliew/robocup-2018#1]
You may remove the `while (Wire.available() < 2);` after the Wire.requestFrom() in the file "robocup-2018/Main/Compass.ino".
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by zwliew** [comment]
Thanks :)
